### PR TITLE
Fix olark docs

### PR DESCRIPTION
**Pull request by jaminben**
Hey @reed Thanks for keeping track of these compatibility issues.  

The above solution is a little bit more robust than the existing solution, but still slightly flakey in some timing circumstances.

Cheers,
Ben

### CODE REVIEW

**Comment by jaminben** [comment]
The current (before this fix) version results in the following errors: 
turbolinkstest-1

**Comment by reed** [comment]
Thanks for submitting this, and sorry for not responding sooner.  Two things before I merge it.  First, you should add your name as a contributor at the top of the page.  Second, I think it'd look better if you moved the comment block from the code block and just had it be normal text.

**Comment by jaminben** [comment]
@reed thanks for the feedback, made changes as you requested.  Cheers, Ben

**Comment by reed** [comment]
Deployed.  Thanks again.

**Pull request merged**
